### ISSUE TITLE
[Feature] advanced Workload selector

### ISSUE THREAD

**Issue by StevenLeiZhang** [openkruise/rollouts#114]
So far ,User use "workloadRef" to specify the target workload. Need one new feature let user specify customized workload selector ,such as "label selector"

**Comment by veophi** [comment]
Do you mean you want to config multi-workloads via one rollout?

**Comment by veophi** [comment]
Maybe, we need a rollout-distributor to generator a rollout to each workload. @StevenLeiZhang

**Comment by StevenLeiZhang** [comment]
> 

No,
```
    workloadRef:
      apiVersion: apps/v1
      kind: Deployment
      name: echoserver
```
That means all the deployments will be hooked by Kruise-rollut. But generally, various workload runs in k8s, use may only want kruise-rollout hook someones. 
I want some conditions,(for example, workload with labels "k1=v1") to specify which one should be hooked.
