### ISSUE TITLE
Kruise Rollout: Traffic Graying, Batch Release, Metrics Analysis 

### ISSUE THREAD

**Issue by zmberg** [openkruise/rollouts#12]
**What would you like to be added:**

Kruise Rollout Features:
- Traffic graying (Canary, Blue-Green Release, A/B Test)
- batch release (Deployment, CloneSet)
- post-release check (Metrics Analysis, hook)

CRD is defined as follows:
```yaml
apiVersion: rollouts.kruise.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  strategy:
    canary:
      steps:
        ## the first 20% grayed out replicas, and 20% of the traffic
        - weight: 20
          ## Manual confirmation of continuation
           pause: {}
      trafficRouting: 
        service: echoserver  # required
        ## nginx ingress 
        type: nginx
        nginx:
          ingress: echoserver  # required
  objectRef: 
    workloadRef: 
      apiVerison: apps/v1
      kind: Deployment
      name: echoserver
```
