### ISSUE TITLE
Support Traffic Graying for Istio Envoy

### ISSUE THREAD

**Issue by zmberg** [openkruise/rollouts#13]
**What would you like to be added:**

Rollout Support Traffic Graying for Istio Envoy, as follows:
```yaml
apiVersion: rollouts.kruise.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  strategy:
    canary:
      steps:
        ## the first 20% grayed out replicas, and 20% of the traffic
        - weight: 20
          ## Manual confirmation of continuation
           pause: {}
      trafficRouting: 
        service: echoserver  # required
        ## istio
        type: istio
        istio:
          virtualService: echoserver  # required
  objectRef: 
    workloadRef: 
      apiVerison: apps/v1
      kind: Deployment
      name: echoserver
```
