### ISSUE TITLE
A/B发布 matches 字段貌似和文档不一致

### ISSUE THREAD

**Issue by git2017-jpg** [openkruise/rollouts#133]
文档：https://openkruise.io/zh/rollouts/user-manuals/api-specifications/

案例中使用
```yaml
matches:
          - headers:
              - type: Exact # or "RegularExpression"
                key: <matched-header-key>
                value: <matched-header-value, or reg-expression>
```
                
报错：Error from server (BadRequest): error when creating "demo_rollout.yaml": Rollout in version "v1alpha1" cannot be handled as a Rollout: strict decoding error: unknown field "spec.strategy.canary.steps[0].matches[0].headers[0].key"

源代码中：rollouts/api/v1alpha1/rollout_types.go

```go
type HttpRouteMatch struct {
	Headers []gatewayv1alpha2.HTTPHeaderMatch `json:"headers,omitempty"`
}
```

```go
type HTTPHeaderMatch struct {
	Type *HeaderMatchType `json:"type,omitempty"`
	Name HTTPHeaderName `json:"name"`
	Value string `json:"value"`
}
```

key目前应该换成name吗
