### ISSUE TITLE
Rollout and kubevela build multi-cluster publishing capabilities together

### ISSUE THREAD

**Issue by zmberg** [openkruise/rollouts#14]
**What would you like to be added:**

Rollout itself is more focused on grayscale within a single cluster, and the capabilities for multiple clusters need to be built with kubevela, as follows:

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: podinfo
spec:
  components:
    traits:
      - type: kruise-rollout
        properties:
          canary:
            steps:
              - weight: 20
                 pause: {}
            trafficRouting:
              type: nginx
```
