### ISSUE TITLE
[Feature] Rollout Strategy add mutli-batch Strategy 

### ISSUE THREAD

**Issue by zmberg** [openkruise/rollouts#148]
Currently Rollout only supports one configuration for canary, and then mutli-batch is also integrated into the canary configuration. It feels possible to separate the two configurations and add a separate mutli-batch strateg, for examples:
```yaml
apiVersion: rollouts.kruise.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  objectRef:
    workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: workload-demo
  strategy:
    canary:
      steps:
      - weight: 20
    batches:
      - replicas: 1
      - replicas: 20%
      - replicas: 40%
      - replicas: 60%
      - replicas: 100%  
```
