### ISSUE TITLE
Improve the current Deployment batch release solution

### ISSUE THREAD

**Issue by zmberg** [openkruise/rollouts#15]
**What would you like to be added:**

The current batch release program for Deployment, the extreme case (as follows) there is a double resource situation, the subsequent optimization to solve:
```yaml
apiVersion: rollouts.kruise.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  strategy:
    canary:
      steps:
        ## the first 20% grayed out replicas, and 20% of the traffic
        - weight: 20
          ## Manual confirmation of continuation
           pause: {}
        -  weight: 40
            pause: {duration: 60}
        -  weight: 60
            pause: {duration: 60}
       -  weight: 80
           pause: {duration: 60}
       -  weight: 100
           pause: {duration: 60}
  objectRef: 
    workloadRef: 
      apiVerison: apps/v1
      kind: Deployment
      name: echoserver
```

So currently for Deployment Rollout, it is recommended to configure it in the following way:
```yaml
apiVersion: rollouts.kruise.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  strategy:
    canary:
      steps:
        ## the first 20% grayed out replicas, and 20% of the traffic
        - weight: 20
          ## Manual confirmation of continuation
           pause: {}
      trafficRouting: 
        service: echoserver  # required
        ## nginx ingress 
        type: nginx
        nginx:
          ingress: echoserver  # required
  objectRef: 
    workloadRef: 
      apiVerison: apps/v1
      kind: Deployment
      name: echoserver
```
