### ISSUE TITLE
Rollout release process supports post-checking, Metrics analysis

### ISSUE THREAD

**Issue by zmberg** [openkruise/rollouts#16]
**What would you like to be added:**

Rollout release process supports post-checking, Metrics analysis, as follows:
```yaml
apiVersion: rollouts.kruise.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  strategy:
    canary:
      steps:
        ## the first 20% grayed out replicas, and 20% of the traffic
        - weight: 20
          ## Manual confirmation of continuation
           pause: {}
      trafficRouting: 
        service: echoserver  # required
        ## nginx ingress 
        type: nginx
        nginx:
          ingress: echoserver  # required
      analysis:
         templates:
         - templateName: success-rate
         startingStep: 2 # delay starting analysis run until setWeight: 40%
           args:
           - name: service-name
             value: echoserver-svc.default.svc.cluster.local  
  objectRef: 
    workloadRef: 
      apiVerison: apps/v1
      kind: Deployment
      name: echoserver
```
