### ISSUE TITLE
变更发布计划缩容Replicas不生效

### ISSUE THREAD

**Issue by lujiajing1126** [openkruise/rollouts#203]
首先创建一个Rollout，

```yaml
apiVersion: rollouts.kruise.io/v1beta1
kind: Rollout
metadata:
  name: rollouts-reviews
  namespace: default
spec:
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reviews
  strategy:
    canary:
      enableExtraWorkloadForCanary: false
      steps:
      - replicas: 1
        matches:
        - headers:
          - name: x-env-flag
            type: Exact
            value: canary
      - replicas: 50%
        traffic: 30%
      trafficRoutings:
      - service: reviews
        customNetworkRefs:
        - apiVersion: networking.istio.io/v1alpha3
          kind: VirtualService
          name: reviews
```

通过变更Deployment的镜像并执行`k kruise rollout approve rollouts/rollouts-reviews -n default`进入到第二步，即

```yaml
      - replicas: 50%
        traffic: 30%
```

Deployment声明了4个副本，这时候有2个stablePod，2个canaryPod。然后变更发布计划，把`replicas`变更成10%，理论上应该变成1个canaryPod，但这个时候没有触发Deployment的变更，因为`BatchRelease`在reconcile过程中会检查，

```go
// IsCurrentMoreThanOrEqualToDesired return true if current >= desired
func IsCurrentMoreThanOrEqualToDesired(current, desired intstr.IntOrString) bool {
	currentNum, _ := intstr.GetScaledValueFromIntOrPercent(&current, 10000000, true)
	desiredNum, _ := intstr.GetScaledValueFromIntOrPercent(&desired, 10000000, true)
	return currentNum >= desiredNum
}
```

这时候因为当前的副本数超过了desired数量，所以不会触发更新。

不知道是不是预期的行为？如果是预期的，这里的考量是什么？
