### ISSUE TITLE
多批次发布是否可以支持同时控制多个版本的发布

### ISSUE THREAD

**Issue by lizhipeng629** [openkruise/rollouts#227]
例如我有一个kruise StatefulSet的负载，10个副本，初始镜像为v1，并且使用了多批次发布,分3批更新。我的负载可能同时存在v1，v2，v3等版本的副本。
例如
- 先更新为v2，发布的step2，此时5个副本为v1,5个副本为v2，
- 然后此时更新为v3，1个副本为v3，4个副本为v2，5个副本为v1
- 此时我想继续v2的发布，将剩余的v1副本都更新为v2，能支持吗
```
apiVersion: rollouts.kruise.io/v1beta1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  workloadRef:
    apiVersion: apps.kruise.io/v1beta1
    kind: StatefulSet
    name:  volern-gs
  strategy:
    canary:
      enableExtraWorkloadForCanary: false
      steps:
      - replicas: 1
      - replicas: 50%
      - replicas: 100%
  ```
