### ISSUE TITLE
关于kruise Rollout 的自动执行灰度发布

### ISSUE THREAD

**Issue by HelonLee135** [openkruise/rollouts#233]
apiVersion: rollouts.kruise.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
  namespace: xiaodu-test
  annotations:
    rollouts.kruise.io/rolling-style: partition
spec:
  objectRef:
    workloadRef:
      apiVersion: apps/v1
      kind: Deployment
      name: auth
  strategy:
    canary:
      steps:
      - replicas: 1
        matches:
        - headers:  #设置一个请求头，根据请求头来路由到下面的10% 流量中
          - name: user-agent
            type: Exact
            value: xiaodu
        weight: 10  # 10% 流量进入新版本
        pause: {}
      - replicas: 50%  #这是第二步，我希望第二步到最后一步都是自动执行的。貌似不支持这个操作，请问有人知道该怎么做吗？
      - replicas: 100%

**Comment by furykerry** [comment]
if you does not want human approve in particular step, you can add the duration field, e.g. 

```
apiVersion: rollouts.kruise.io/v1beta1
kind: Rollout
metadata:
  name: rollouts-demo
  namespace: default
spec:
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: workload-demo
  strategy:
    canary:
      steps:
      - replicas: 1
         pause: {}
      - replicas: 50%
         pause:
             duration: 0
      - replicas: 100%
         pause:
             duration: 0
```
you can check the field detail in [doc](https://openkruise.io/rollouts/user-manuals/api-specifications#strategy-api-mandatory)
