### ISSUE TITLE
是否只支持weight方式 

### ISSUE THREAD

**Issue by trestea** [openkruise/rollouts#60]
strategy:
    canary:
      # canary published, e.g. 20%, 40%, 60% ...
      steps:
      # routing 5% traffics to the new version
      - weight: 5 
      # Manual confirmation of the release of the remaining pods
        pause: {}
      # optional, The first step of released replicas. If not set, the default is to use 'weight', as shown above is 5%.
        replicas: 20%
这个配置是否支持weight 这种配置，有没有其他方式。

**Comment by zmberg** [comment]
Let's make a schedule to support it

**Comment by no-frown** [comment]
```yaml
apiVersion: rollouts.kruise.io/v1alpha1
kind: Rollout
metadata:
  name: echoserver-rollout
  namespace: sgt
spec:
  objectRef:
    workloadRef:
      apiVersion: apps/v1
      kind: Deployment
      name: echoserver
  strategy:
    canary:
      steps:
      - replicas: 1
        pause: {}
      - replicas: 2
        pause: {duration: 60}
      - replicas: 2
      trafficRoutings:
        - gateway:
            httpRouteName: echoserver
          service: echoserver
```





Error from server: error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"rollouts.kruise.io/v1alpha1\",\"kind\":\"Rollout\",\"metadata\":{\"annotations\":{},\"name\":\"echoserver-rollout\",\"namespace\":\"sgt\"},\"spec\":{\"objectRef\":{\"workloadRef\":{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"name\":\"echoserver\"}},\"strategy\":{\"canary\":{\"steps\":[{\"pause\":{},\"replicas\":1},{\"pause\":{\"duration\":60},\"replicas\":2},{\"replicas\":2}],\"trafficRoutings\":[{\"gateway\":{\"httpRouteName\":\"echoserver\"},\"service\":\"echoserver\"}]}}}}\n"}},"spec":{"strategy":{"canary":{"steps":[{"pause":{},"replicas":1},{"pause":{"duration":60},"replicas":2},{"replicas":2}]}}}}
to:
Resource: "rollouts.kruise.io/v1alpha1, Resource=rollouts", GroupVersionKind: "rollouts.kruise.io/v1alpha1, Kind=Rollout"
Name: "echoserver-rollout", Namespace: "sgt"
for: "a.yaml": admission webhook "vrollout.kb.io" denied the request: Spec.Strategy.Canary.Steps[0].steps: Invalid value: []v1alpha1.CanaryStep{v1alpha1.CanaryStep{Weight:(*int32)(nil), Replicas:(*intstr.IntOrString)(0xc000d6be20), Pause:v1alpha1.RolloutPause{Duration:(*int32)(nil)}}, v1alpha1.CanaryStep{Weight:(*int32)(nil), Replicas:(*intstr.IntOrString)(0xc000d6bec0), Pause:v1alpha1.RolloutPause{Duration:(*int32)(0xc0019e1f18)}}, v1alpha1.CanaryStep{Weight:(*int32)(nil), Replicas:(*intstr.IntOrString)(0xc000d6bf40), Pause:v1alpha1.RolloutPause{Duration:(*int32)(nil)}}}: weight cannot be empty for traffic routing

openkruise/kruise-rollout:v0.2.0 我也遇到了，weight 不允许 为空

**Comment by zmberg** [comment]
Because you have configured trafficRoutings, you need traffic scheduling, you must configure weight. why you want weight to be empty?

**Comment by no-frown** [comment]
嗯 了解了

因为之前参考微信文章的例子 
> https://mp.weixin.qq.com/s/LAg3jwGEwPF9MafcKlfmBA
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: echoserver
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: echoserver
          image: cilium/echoserver:latest
---
apiVersion: rollouts.kruise.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  objectRef:
    workloadRef:
      apiVersion: apps/v1
      kind: StatefulSet
      name: echoserver
  strategy:
    canary:
      steps:
      - replicas: 1
        pause: {}
      - replicas: 2
        pause: {duration: 60}
      - replicas: 2
```
